# references:
# * http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode7.1
# cache: cocoapods
before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - pod repo update

xcode_workspace: Example/iosMathEditor.xcworkspace # path to your xcodeproj folder
xcode_scheme: iosMathEditor-Example
xcode_sdk: iphonesimulator
